@api = http://localhost:5555
@s3_key = CZf2R__BwHq5oTRDpBlv2au6yDU-GzQOCyHNyBbyqACyUW2Z0wkf3zVY4pQEr2V8odOE1QlJVmty6kQmmTTWhfqlGgWO-QMSdZkgWchWuIqIeU3bFZlVvGNfE29ev6GV1J8WmiJ6XzMac3JFp1Ht_6w
@api_key = key
@api_secret = secret
@subscriber = 20000000

### Get Token
# @name auth
POST {{api}}/auth/token
Authorization: Basic {{api_key}}:{{api_secret}}
Content-Type: application/json

{
    "sub": "{{subscriber}}"
}

### Assign Token to Variable
@token = {{auth.response.body.access_token}}

### Health Check
GET {{api}}/health-check
Authorization: Bearer {{token}}
### Get Image
GET {{api}}/image?key={{s3_key}}

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=400x400

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=300x300

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=200x200

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=100x100

