@api = http://localhost:5555
@s3_key = TEeq8BmdOMryyiZPvX3mZejml55b9EzqBJXszhLxqU3F2pK4V0o3Yu8w9YSWaB9pE4mFY8i0u2pYvXyGHTx4RNQDS6Ko5fPvZd6FW%2FlEf7Fjis4a9ZG09IAmWqi3EMGxR1N6ErwUBeldxOzF35rVrAkamSHX2RnHx6rFS2HENkojlFQoRGpfmnDrXiSbIM9RS87dgNXKKCr%2FCZgmGf0zT66pZK7v
@api_key = key
@api_secret = secret
@subscriber = 20000000

### Get Token
# @name auth
POST {{api}}/auth/token
Authorization: Basic {{api_key}}:{{api_secret}}
Content-Type: application/json

{
    "sub": "{{subscriber}}"
}

### Assign Token to Variable
@token = {{auth.response.body.access_token}}

### Health Check
GET {{api}}/health-check
Authorization: Bearer {{token}}
### Get Image
GET {{api}}/image?key={{s3_key}}

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=200x200

### Get Image with Size
GET {{api}}/image?key={{s3_key}}&size=100x100

